//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageS3WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int setID { get; set; }
        public string setName { get; set; }
        public string setDescription { get; set; }
        public string setSettings { get; set; }
        public int setOrder { get; set; }
    }
}
